name = "NetworkVisualizer"
uuid = "8701a782-b1b0-47ba-9e53-901d719c6388"
authors = ["Jean-Fran√ßois BAFFIER (@Azzaare)"]
version = "0.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Oxygen = "df9a0d86-3283-4920-82dc-4555fc0d1d8b"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
Dates = "1.11.0"
HTTP = "1.10.15"
JSON3 = "1.14.1"
Oxygen = "1.5.14"
Pkg = "1.11.0"
Random = "1.11.0"
TestItems = "1.0.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
